<!-- This .Rmd file is set up to run either independently by checking for 
the presence of necessary objects in the global environment and running 
related scripts if not, or also as a child to the "main-doc". For that latter
reason, comments and headings that are not relevant to a final report to
pubic audiences are suppressed or moved to code chunks that can optionally be 
`echo`ed as desired. -->

```{r}
# set flags for running this 01b script
print_documentation <- FALSE
```

```{r }
# run scripts for necessary packages and objects as necessary
if (!"meanNA"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("method--read-customization-file.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
```

```{r set parameters for acs1}
# Set a parameter for the minimum hours of usual hours worked to qualify for benefits
work_hrs_threshold <- 20
```


```{r read in acs1 data and documentation}
my_pums <- 
  pums_variables %>% 
  filter(year   == {base_year},
         survey == "acs1") %>% 
  select(var_code, var_label, level, val_min, val_max, val_label)

acs1_save_file <- glue("{input_path}census_acs1_{base_year}_{my_output_tag}.csv")
if (!file.exists(acs1_save_file)) {
  source("pull--acs1-microdata.R")
} else {
  acs1 <- fread(file = acs1_save_file)
}
```

```{r view metadata on relevant fields for the acs1}
view_acs1_fields <- 
  function(
    acs1_year,
    fields = 
      c("RELP|RELSHIPP", # Relationships
        "SCHL",          # educational attainment
        "INDP",          # industry
        "RAC2P", "HISP", # race and ethnicity
        "SCH",           # school enrollment status 
        "ESR",           # work status
        "WKHP",          # usual hours worked
        "DIS",           # Disability recode (1 = with disability, 2 = without disability)
        "SSIP",          # SSI receipt
        "VPS",           # Veteran period of service (bb -- less than 17, no active duty)
        "DRATX",         # Veteran service-connected disability rating (Y/N)
        "AGEP",          # age
        "POVPIP",        # poverty to income ratio
        "PWGTP", "YEAR"  # personal weight and year
        )
  ) {
    pums_variables %>% 
      filter(
        survey == "acs1",
        year == acs1_year,
        str_detect(
          var_code,
          paste(fields, collapse = "$|^")
        )
      ) %>% 
      View()
  }

if (FALSE) {
  view_acs1_fields(2023) # # /!\ 2024 variables are not yet loaded in tidycensus  
}

```


```{r ensure that ACS1 PUMA values are character to be consistent with other datasets}
acs1 <- 
  acs1 %>% 
  mutate(
    PUMA = pad_num_left(PUMA, width = 5)
  )
```

```{r develop fields for the relationship variable depending on its source}
if (base_year <= 2018) {
  acs1 <- 
    acs1 %>% 
    mutate(
      cRel = 
        case_when(
          rel_var == 00                    ~ "Head",
          rel_var == 01                    ~ "Spouse",
          rel_Var %in% c("02", "03", "04") ~ "Child",
          TRUE ~ "Other relationship"
        )
    )
} else {
  acs1 <- 
    acs1 %>% 
    mutate(
      cRel = 
         case_when(
           rel_var == 20          ~ "Head",
           rel_var %in% c(21, 23) ~ "Spouse",
           rel_var %in% 25:27     ~ "Child",
           TRUE ~ "Other relationship"
         )
    )
}
```


### Sample Restrictions

ACS 1-Year microdata for `r base_year` are downloaded from the [Census Application Program Interface (API)](https://www.census.gov/data/developers/data-sets/acs-1year.html) and subset to households not living in group quarters, and to `r my_state_abbr` records.

```{r subset microdata}
# TYPE (Census) -- 1 - Housing unit, 2 - group quarters
# Sample restricted to housing unit only

my_state_fip <- 
  fips_codes %>% 
  filter(state == my_state_abbr) %>% 
  pull(state_code) %>% 
  unique()

acs1 <- 
  acs1 %>% 
  filter(
    TYPEHUGQ %in% c(1),
    STATE == my_state_fip,
    YEAR == max(YEAR)
  )

# If county has been specified, load geographic data to perform subsetting to
# relevant PUMAs
if (exists("my_county_fip")) {
  load(glue("{output_path}geo_data_{my_output_tag}.Rda"))
  acs1 <- acs1 %>% filter(PUMA %in% geo_crosswalk$PUMA)
}
```


```{r ensure all households have a householder}
stopifnot(
  all(
    acs1 %>% 
      summarize(
        .by = c(YEAR, SERIALNO),
        has_hoh = maxNA(cRel == "Head")
      ) %>% 
      pull(has_hoh) == 1
  )
)
```

```{r recode acs1 fields}
acs1_recoded <- 
  acs1 %>% 
  mutate(
   
    # Recode Gender
    cGender = 
      case_match(
        SEX,
        1 ~ "Male",
        2 ~ "Female"
      ),
    bGender_M = 1*(cGender == "Male"),
    bGender_F = 1*(cGender == "Female"),
     
    # Create age groups
    cAge = 
      case_when(
        # AGEP %in%  0:5  ~ "Age0to5",
        # AGEP %in%  6:14 ~ "Age6to14",
        # AGEP %in% 15:19 ~ "Age15to19",
        AGEP %in%  0:19 ~ "Age0to19",
        AGEP %in% 20:64 ~ "Age20to64",
        AGEP >= 65      ~ "Age65plus"
      ),
    bAge0to5   = 1*between(AGEP,  0,  5),
    bAge6to14  = 1*between(AGEP,  6, 14),
    bAge15to19 = 1*between(AGEP, 15, 19),
    bAge0to19  = 1*between(AGEP,  0, 19),
    bAge20to64 = 1*between(AGEP, 20, 64),
    bAge65plus = 1*(AGEP >= 65),
    
    # Recode race and ethnicity
    cRace =
      case_when(
        RAC2P == 1000 ~ "white", 
        RAC2P == 2000 ~ "black", 
        TRUE ~ "other_multiple"),
    bHispanic = 1*(HISP != 1) ,
    
    # Recode school enrollment status
    cSchEnr =
      case_match(
        SCH,
        0 ~ "LtAge3",
        1 ~ "Not Attending",
        2 ~ "Public school or college",
        3 ~ "Private school or college"
      ),
    bInSch = 1*(str_detect(cSchEnr, "school or college")),
    
    # Recode educational attainment
    cEduc = 
      case_when(
        between(SCHL,  2, 15) ~ "LtHs", 
        between(SCHL, 16, 17) ~ "HS", 
        between(SCHL, 18, 20) ~ "SomeColl", 
        between(SCHL, 21, 21) ~ "Coll", 
        between(SCHL, 22, 24) ~ "Grad", 
        TRUE ~ "NA" # Default value is NA
      ), 
    bEduc_LtHs     = 1*(cEduc == "LtHs"),
    bEduc_HS       = 1*(cEduc == "HS"),
    bEduc_SomeColl = 1*(cEduc == "SomeColl"),
    bEduc_Coll     = 1*(cEduc == "Coll"),
    bEduc_Grad     = 1*(cEduc == "Grad"),
    
    # Recode usual hours worked per week
    has_usual_hrs_worked = 1*(!is.na(as.numeric(WKHP))),
    usual_hrs_worked = 
      case_when(
        has_usual_hrs_worked == 0 ~ 0,
        TRUE ~ as.numeric(WKHP)
      ),
    
    # Recode employment status
    cEmpl = 
      case_match(
        ESR,
        0 ~ "ltAge16",
        1 ~ "Employed, at work",
        2 ~ "Employed, has Job but not at work",
        3 ~ "Unemployed",
        4 ~ "Armed Forces, at work",
        5 ~ "Ameved forces, has job but not at work",
        6 ~ "Not in labor force"
      ),
    bEmpl_elig = 1*str_detect(cEmpl, "Employed|Armed Forces"),
    bEmpl_metHrsThres_elig = 1*(bEmpl_elig & (usual_hrs_worked >= work_hrs_threshold)),
    
    # Categorize industry of work
    cIndustry = bin_industry(INDP), # bin_industry() is defined in the `helper` script
    
    # Recode disability information
    bDisab  = 1*(DIS == 1),
    bHasSsi = 1*(SSIP > 0)
    
  )
```

```{r check results of recoding}
if (FALSE) {
  acs1_recoded %>% 
    select(
      SERIALNO, SPORDER, rel_var, cRel, AGEP, cAge, 
      SEX, cGender, bGender_M, bGender_F, 
      RAC2P, cRace, HISP, bHispanic, SCH, cSchEnr, SCHL, cEduc, 
      ESR, bEmpl_elig, WKHP, usual_hrs_worked, DIS, bDisab, SSIP, bHasSsi 
    ) %>% 
    View("Check Recodings")
}
```


```{r summarize household-level values}
acs1_adults <-
  acs1_recoded %>% 
  mutate(
    .by = c(YEAR, SERIALNO),
    fam_size = n(),
    bAge0to5_present   = maxNA(bAge0to5),
    bAge6to14_present  = maxNA(bAge6to14),
    bAge15to18_present = maxNA(bAge15to19),
    bAge0to14_present  = maxNA(bAge0to5 | bAge6to14)
  ) %>% 
  
  # Subset only to householder and spouse (if present) data
  # /!\ Note, there are cases of households where working adults are living with
  # parents, where the elderly parents are listed as the heads of household.
  filter(
    cRel %in% c("Head", "Spouse")
  ) %>% 
  
  # Summarize presence of spouse and all working/school enrolled status
  summarize(
    .by = c(YEAR, SERIALNO, fam_size),
    bSpousePresent = maxNA(cRel == "Spouse"),
    bAdults_all_work_sch         = minNA(bInSch | bEmpl_elig),
    bAdults_all_workThresh_sch   = minNA(bInSch | bEmpl_metHrsThres_elig)
  ) 

```


```{r examine build of household fields}
# Allow examination of cases
if (FALSE) {
  check <- 
    merge(
      acs1 %>% select(YEAR, SERIALNO, cRel, SEX, AGEP, SCH, ESR),
      acs1_adults[j = .(YEAR, SERIALNO, fam_size, spouse_present, all_work_sch)],
      all = TRUE,
      by = c("SERIALNO", "YEAR")
    )
  View(check)
  
  # Calculate how many indicators are missing
  check %>% 
    summarize(
      pct_missing_spouse_info     = mean(is.na(spouse_present)),
      pct_missing_work_info       = mean(is.na(all_work_sch)),
      pct_missing_workThresh_info = mean(is.na(bAdults_all_workThresh_sch)),
    )
  
}
```

```{r combine individual and adult records}
acs1_family <-
  merge(
    acs1_recoded,
    acs1_adults,
    by = c("YEAR", "SERIALNO")
  )
```

```{r get fpl threshold for prog for ACS1 calcs}
# It's not strictly the case that this is provided directly by users, because a
# custom income threshold such as based on state median income may have been 
# provided

prog_inc_thresh_fpl <- get_fpl_thresh_for_prog()
```

```{r develop partitions of income and work eligibility for SAE}

# /!\ This is is where ABAWD considerations could be built in, although those are
# most consequentially reflected in CPS data as those constructions are what
# define the ultimate targets
acs1_elig <- 
  acs1_family %>% 
  mutate(
    fam_incpov_ratio = POVPIP / 100,
    
    #cFam_incpov_ratio_cat_mix     = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 0.50, 1.00, 2.00, 4.00)),
    cFam_incpov_ratio_cat_by100   = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = seq(0, 4, by = 1.0)),
    #cFam_incpov_ratio_cat_hs_prog = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 1.00, prog_inc_thresh_fpl/100, 4.00)),
    cFam_incpov_ratio_cat_with130 = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 0.75, 1.30, 2.00, 4.00)),
    # fam_incpov_ratio_cat_by50    = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = seq(0, 4, by = 0.5)),
    # fam_incpov_ratio_cat_by75    = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 0.75, 1.50, 2.25, 4.00)),
    
    cWorkElig       = ifelse(bAdults_all_workThresh_sch == 1, "WorkElig",       "NotWorkElig"),
    cWorkEligThresh = ifelse(bAdults_all_work_sch       == 1, "WorkEligThresh", "NotWorkEligThresh"),
    cSpousePresent  = ifelse(bSpousePresent == 1, "SpousePresent", "NoSpousePresent"),
    
    #work_spouse_status    = paste_(cWorkElig, cSpousePresent),
    cWork_incpov_status130 = paste_(cWorkElig, cFam_incpov_ratio_cat_with130),
    #cWork_incpov_status100 = paste_(cWorkElig, cFam_incpov_ratio_cat_by100),
    #cWork_incpov_statushs  = paste_(cWorkElig, cFam_incpov_ratio_cat_hs_prog),
    
    cWorkThresh_incpov_status130 = paste_(cWorkEligThresh, cFam_incpov_ratio_cat_with130),
    #cWorkThresh_incpov_status100 = paste_(cWorkEligThresh, cFam_incpov_ratio_cat_by100),
    #cWorkThresh_incpov_statushs  = paste_(cWorkEligThresh, cFam_incpov_ratio_cat_hs_prog),
  
    obs_weight = PWGTP
  )
  
```

```{r merge in the custom income thresholds if specified}
if (exists("custom_income_thresh")) {
  # Check that all family sizes present in the data are represented in the custom
  # spec file
  if (!maxNA(acs1_elig$fam_size) %in% custom_income_thresh$fam_size) {
    
    warning(
      glue(
        "The `custom_income_thresh` table does not contain all family ",
        "sizes present in the ACS 1-year microdata. It must reflect ",
        "family sizes up through {maxNA(acs1_elig$fam_size)}."
      )
    ) 
  }
  
  acs1_elig <- 
    acs1_elig %>% 
    merge(
      custom_income_thresh,
      by = "fam_size",
      all.x = TRUE) %>% 
    mutate(
      incratio_thresh = FINCP / inc_thresh  
    )
    
}
```

```{r generate prog eligibility flags}
# Generate multiple flags of program eligibility at the potentially-multiple
# income-to-threshold ratios specified

# Note: these are used in 03b to generate PUMA-level age breakdowns within
# eligibility status

# Determine which income ratio to use, based on whether custom values were specified
if (exists("custom_income_thresh")) {
  acs1_elig <- acs1_elig %>% mutate(my_incratio = incratio_thresh)
} else {
  acs1_elig <- acs1_elig %>% mutate(my_incratio = fam_incpov_ratio)
}

# Generate one eligibility field for each cutpoint specified
acs1_elig <-
  acs1_elig %>% 
  as.data.table() %>% 
  .[j = paste0("bProg_elig_inc_", local_prog_incratio_cuts) :=
      lapply(local_prog_incratio_cuts, 
             function(x) {
               1*(my_incratio <= x/100)
             })] %>% 
  .[j = paste0("bProg_elig_incwork_", local_prog_incratio_cuts) :=
      lapply(local_prog_incratio_cuts, 
             function(x) {
               1*bAdults_all_workThresh_sch*(my_incratio <= x/100)
             })]
  
```

```{r review key constructions}
if (FALSE) {
  # View all households
  acs1_elig_keymeasures <- 
    acs1_elig %>% 
    select(
      SERIALNO, SPORDER, AGEP, cAge, cRel, cEduc, 
      POVPIP, fam_incpov_ratio, 
      cEmpl, cSchEnr, usual_hrs_worked, bEmpl_elig, 
      bEmpl_metHrsThres_elig, cFam_incpov_ratio_cat_with130, cWorkThresh_incpov_status130
    )
  
  View(acs1_elig_keymeasures, "Check key ACS1 constructions")
  
  acs1_elig_keymeasures_highInc_notQual <- 
    acs1_elig_keymeasures %>% 
    filter(
      cWorkThresh_incpov_status130 == "NotWorkEligThresh_400%+"
    ) %>% 
    View("ACS1 - high earners, not work qualifying")
}
```


```{r check on small cells in the partitions constructed above, eval = developer_mode}
# /!\ Note: this needs to be checked carefully for each given setting, because
# the choices here may need to be adjusted based on the data
partition_vars <- sub_cn(acs1_elig, "cFam_incpov|cWorkThresh_incpov")

for (pv in partition_vars) {
  my_plot <- 
    acs1_elig %>% 
    summarize(
      .by = c(pv, "PUMA"),
      n = n()) %>% 
    ggplot() +
    aes(
      x = n,
      color = get(pv)
    ) +
    geom_density(
      linewidth = 1
    ) +
    geom_vline(
      xintercept = 10
    ) +
    # scale_x_continuous(
    #   limits = c(0, 50)
    # ) +
    labs(
      title = pv
    ) +
    theme(
      axis.text = element_text(angle = 90)
    )
  print(ggplotly(my_plot, tooltip = "color"))
  #print(my_plot)
}
```


```{r combine cells from the above constructions to eliminate small cells}
# /*\ This is something that should be freshly checked as part of each setting
# Developer note: as a rough guide, we look to combine cells that have most
# of their density below cell sizes of 10. An exception to this is that we keep
# `fam_incpov_ratio_cat_mix` which has a cell of 50-100% FPL which we have
# generally found to be small, because it is primarily used to generate estimates
# for 0-50% only, with `fam_incpov_ratio_cat_by100` used as the baseline for 
# other baseline and now-cast estimates.

# While these are all judgment calls, their validity can be assessed by the
# diagnostics produced in the `02a` script which compares the SAE estimates versus
# ACS 1-year values at the PUMA level.

# /*\ Return to this pending review of small partitions above
# acs1_elig <- 
#   acs1_elig %>% 
#   mutate(
#     work_incpov_mix = 
#       case_when(
#         str_detect(
#           work_incpov_statushs,
#           #glue("NotWorkElig_([^0%])")) ~ "NotWorkElig_100%_500%",
#           # Note that this regular expression matches strings
#           # that start with "NotWorkElig" and do *not* follow with 0%
#           # in practice, this groups all larger cells
#           glue("NotWorkElig_(0%|100%)")
#         ) ~ 
#           glue("NotWorkElig_0%_{local_prog_incratio_base}%"),
#         str_detect(
#           work_incpov_statushs,
#           glue("NotWorkElig_[^(0%|100%)]")
#         ) ~
#           glue("NotWorkElig_{local_prog_incratio_base}%+"),
#         TRUE ~ work_incpov_statushs))
#   # Note that we intentionally leave "WorkElig_0%_100%" as an often-smaller
#   # cell because it represents an important single quantity of children in
#   # families that are simultaneously HS and prog eligible

if (FALSE) {
  my_plot <- 
    acs1_elig %>% 
    summarize(
      .by = c(work_incpov_mix, PUMA),
      n = n()
    ) %>% 
    ggplot(
      aes(
        x = n,
        color = work_incpov_mix
      )
    ) +
    geom_density() +
    geom_vline(
      xintercept = 10
    ) +
    scale_x_continuous(
      limits = c(0, 50)
    )
    
  print(ggplotly(my_plot, tooltip = "color"))
}
```


```{r check puma-level patterns in various eligibility status}
# /*\ May need updating based on program eligibility logic
acs1_puma_stats <- 
  acs1_elig %>% 
  summarize(
    .by = c(cAge, PUMA),
    across(
      matches("^bProg_elig_"),
      ~ sumNA(PWGTP * (.x == 1)) / sum(PWGTP)
    )
  )
```

```{r}
prog_elig_cut <- local_prog_incratio_cuts[1]
ggplot(
  acs1_puma_stats,
  aes(
    x = get(glue("bProg_elig_inc_{prog_elig_cut}")),
    y = get(glue("bProg_elig_incwork_{prog_elig_cut}"))
  )
) +
  geom_point() + 
  # geom_abline() +
  scale_x_continuous(
    labels = percent
  ) +
  scale_y_continuous(
    labels = percent
  ) +
  coord_fixed() +
  labs(
    title = "PUMA-level Program Eligibility by Just Income, vs With Work",
    x = glue("% With Income Below {prog_elig_cut} FPL"),
    y = glue("% Work Eligible, With Income Below {prog_elig_cut} FPL")
  ) +
  theme_minimal()
```

```{r remove data sets that will not be used in any future data development}
rm(acs1, acs1_recoded, acs1_adults, acs1_family)
gc()
```

```{r calculate selected statistics at the PUMA level with standard errors to facilitate later checks}

calc_acs1_puma_pov <- function(my_data, indices) {
  # Perform stratified bootstrap sampling of the data, with age and PUMA
  my_data_boot <- 
    my_data[j = .SD[sample(.N, .N, replace = TRUE)],
            by = .(cAge, PUMA)]
  
  my_data_boot[j = .(pct_pov = sum(PWGTP[fam_incpov_ratio <= 1.00]) / sum(PWGTP)),
               by = .(cAge, PUMA)] %>% 
    .[order(cAge, PUMA)] %>% 
    pull(pct_pov)
}

acs1_boot <- boot::boot(acs1_elig, calc_acs1_puma_pov, R = 200)
acs1_puma_stats <- 
  cbind(
    acs1_boot$data[j = .(cAge, PUMA)] %>% unique(),
    data.table(pct_pov       = acs1_boot$t0,
               pct_pov_check = apply(acs1_boot$t, 2, mean)),
    pct_pov_se    = sqrt(apply(acs1_boot$t, 2, var)))
```



```{r}
save(
  acs1_elig,
  acs1_puma_stats,
  file = glue("{output_path}acs1_data_{my_output_tag}.Rda")
)
```