
```{r}
# run scripts for necessary packages and objects as necessary
if (!"meanNA"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("method--read-customization-file.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
```

```{r load the data from the previous stage}
# Load prepped data
for (f in c("geo", "acs1", "pop")) {
  load(file = glue("{output_path}{f}_data_{my_output_tag}.Rda"))
}
load(file = glue("{output_path}Now-cast counts at the tract level, pre-disaggregation - {my_output_tag}.Rda"))
```


### Apply Shares to Disaggregated Age Groups

```{r}
# Create mapping of final age groups of interest to ages from specifications
pop_age_mapped <- 
  pop_age_t_calib %>% 
  mutate(
    age = 
      case_when(
        str_detect(
          age_var, 
          "Age(0to4|5to8|9to15|16to18)" ~ "Age0to18",
          "Age19to25"                   ~ "Age9to25",
          "Age(26to34|35to44)"          ~ "Age26to44",
          "Age(45to54|55to64)"          ~ "Age45to64",
          "Age65plus"                   ~ "Age65plus",
        )
      )
  ) %>% 
  mutate(
    pop_count    = calib,
    pop_count_se = 0 # calib_se
  )

nowcast_parallel_counts <- 
  nowcast_parallel %>% 
  merge(
    pop_age_mapped,
    by = c("GEOID", "age"),
    all.x = TRUE
  ) %>% 
  mutate(
    count    = share*pop_count,
    count_se = se_product(share, pop_count, share_se, pop_count_se)
  )
  
```



### Aggregate Estimates to Larger Geographies

```{r function to add level of aggregation if not already available}
add_agg_level <- function(ests, agg_level) {
  
  if (!agg_level %in% colnames(ests)) {
    if (agg_level == "ZCTA") {
      geo_merge_data <- 
        geo_crosswalk_zcta %>% 
        transmute(
          GEOID    = GEOID, 
          ZCTA     = ZCTA,
          geo_part = TRLANDPCT
        )
    } else if (agg_level == "school") {
      geo_merge_data <-
        geo_crosswalk_sd %>%
        transmute(
          GEOID    = GEOID,
          school   = school,
          geo_part = pct_sd
        )
    } else if (agg_level == "County") {
      geo_merge_data <- 
        geo_crosswalk %>% 
        transmute(
          GEOID    = GEOID, 
          County   = County, 
          geo_part = pct_area
        ) %>% 
        unique()
    } else if (agg_level == "State") {
      geo_merge_data <- 
        geo_crosswalk %>% 
        transmute(
          GEOID    = GEOID, 
          State    = my_state, 
          geo_part = 1
        ) %>% 
        unique()
    } else if (agg_level == "aux_geo_label") {
      geo_merge_data <- 
        geo_crosswalk_aux %>% 
        transmute(
          GEOID         = GEOID, 
          aux_geo_label = aux_geo_label, 
          geo_part      = pct_area
        )
    }
    
    ests <- 
      ests %>% 
      # Note: while merge() is typically used throughout this codebase, we use
      # left_join() here because we have a less-common situation of a large
      # many-to-many merge e.g. in the case of merging to zip codes, where there
      # are many duplicates of GEOID in `ests` because of outcome variable, age
      # and time repeats, as well as in `geo_merge_data` given that tracts often
      # do span multiple zip codes. The `allow.cartesian=TRUE` option in merge()
      # was yielding incorrect and puzzling results.
      left_join(
        geo_merge_data,
        by = "GEOID"
      ) %>% 
      data.table()
  }
  
  if (!"geo_part" %in% colnames(ests)) {
    ests <- mutate(ests, geo_part = 1)
  }
  
  return(ests)
}
```


```{r create function to aggregate tract estimates to higher levels}
agg_tracts_up <- function(ests, agg_level) {
  ests %>%
    add_agg_level(agg_level) %>% 
    summarize(
      .by = c(agg_level, "age", "pd", "outcome_var", "cps_base_recency"),
      
      count        = sumNA(pop_count*share*geo_part),
      count_se     = se_sum(se_product(pop_count*geo_part, share, pop_count_se*geo_part, share_se)),
      pop_count    = sumNA(pop_count*geo_part),
      pop_count_se = se_sum(pop_count_se*geo_part)) %>% 
    mutate(
      share    = count / pop_count,
      share_se = se_proportion(count, pop_count, count_se, pop_count_se)
    )
}
```


```{r implement various levels of geographic aggregation}
# Note -- ZCTA and "aux" calculations may produce a "Detected an unexpected
# many-to-many relationship between `x` and `y`." This is expected, given 
# how this is a feature of crossing geographies.

nowcast_agg_tract <- agg_tracts_up(nowcast_parallel_counts, "GEOID")
nowcast_agg_zip   <- agg_tracts_up(nowcast_parallel_counts, "ZCTA")
nowcast_agg_cty   <- agg_tracts_up(nowcast_parallel_counts, "County")
nowcast_agg_sd    <- agg_tracts_up(nowcast_parallel_counts, "school")
nowcast_agg_st    <- agg_tracts_up(nowcast_parallel_counts, "State")

if (exists("my_aux_geo")) {
  nowcast_agg_aux <- agg_tracts_up(nowcast_parallel_counts, "aux_geo_label")  
}

```

```{r produce simple output of the aggregates}
my_write.csv <- function(x, suffix) {
  x %>% 
    # filter(cps_base_recency == "most_recent") %>% 
    # select(-cps_base_recency) %>% 
    write.csv(file = glue("{output_path}Simple elig output by age, period, and outcome -- {suffix}_{my_output_tag}.csv"),
              row.names = FALSE)
}

my_write.csv(nowcast_agg_tract, "by tract")
my_write.csv(nowcast_agg_zip,   "by zcta")
my_write.csv(nowcast_agg_cty,   "by county")
my_write.csv(nowcast_agg_sd,    "by school districts")
my_write.csv(nowcast_agg_st,    "for entire state")

if (exists("my_aux_geo")) {
  my_write.csv(nowcast_agg_aux, glue("by {my_aux_geo_desc}"))
}

```

```{r save final aggregates}
to_save <- 
  c("nowcast_agg_tract",
    "nowcast_agg_zip",
    "nowcast_agg_cty",
    "nowcast_agg_sd",
    "nowcast_agg_st")

if (exists("my_aux_geo")) {
  to_save <- c(to_save, "nowcast_agg_aux")
}

save(
  list = to_save,
  file = glue("{output_path}Final ELPEP Estimates in Multiple Geographic Aggregates - {my_output_tag}.Rda")
)
```

