
<!-- This .Rmd file is set up to run either independently by checking for 
the presence of necessary objects in the global environment and running 
related scripts if not, or also as a child to the "main-doc". For that latter
reason, comments and headings that are not relevant to a final report to
pubic audiences are suppressed or moved to code chunks that can optionally be 
`echo`ed as desired. -->

```{r}
# set flags for running this cps script
print_documentation <- FALSE
developer_mode <- FALSE
```

```{r}
# run scripts for necessary packages and objects as necessary
if (!"meanNA"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("method--read-customization-file.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
```

```{r set parameters for cps}
# Set a parameter for the minimum hours of usual hours worked to qualify for benefits
work_hrs_threshold <- 20
```


```{r read in cps data and documentation}
# Remove the file extension from the `cps_raw` filename
cps_raw <- str_replace(cps_raw, "\\.\\w+", "")
cps_documentation <- read_ipums_ddi(glue("{input_path}{cps_raw}.xml"))
```

```{r view metadata on relevant fields for the cps}
view_cps_fields <- 
  function(
    fields = 
      c("FAMINC", 
        "ASECFLAG", 
        "STATEFIP", 
        "RELATE",
        "CPSID", "PWGTP", "YEAR"  # personal weight and year
      )) {
    
    show_ipums_doc(
      cps_documentation
    )
  }

# Display codebook data -- note: it's lengthy
if (FALSE) {
  view_cps_fields()  
}

```

<!-- Current Population Survey (CPS) microdata are manually downloaded from the [IPUMS CPS](https://cps.ipums.org/cps/) site from `r base_year` through the most recent available month. -->

<!-- The sample is restricted to families of head of householders. This is practically driven by the availability of family income as available only for those individuals who are related to the head of household. -->

<!-- Hawaii and Alaska are dropped, as they follow different federal poverty guidelines than other states, and are expected to have distinct economic dynamics. -->

<!-- Note that subsetting to match households with both pre and post measures only occurs later, at the point that the method calculates transition ratios. We perform this match--and implicit subsetting--at that stage because a range of choices is may be reasonable and we save the application of discretion for that later stage. -->

```{r read and subset cps microdata}
cps <- fread(file = glue("{input_path}{cps_raw}.csv.gz"))
cps_sub <- 
  cps %>% 
  filter(
    CPSID != 0,                        # This rules out ASEC over-sample households (see documentation on `CPSID`)
    ASECFLAG == 2 | is.na(ASECFLAG),   # This excludes March ASEC sample 
                                       # Using both ASEC and monthly causes some issues --
                                       # e.g., generate WTFINL == NA for March ASEC; double counts individuals for March
                                           # See https://cps.ipums.org/cps/cps_linking_documentation.shtml
    !STATEFIP %in% c(2, 15),           # This excludes HI and AK
     between(RELATE, 101, 1001)        # This subsets to only related members of the household
  ) %>%        
  select(-COUNTY, -OCC, -CLASSWKR) # dropping variables not currently used.

# Check that only primary family unit is retained
stopifnot(all(cps_sub$FAMUNIT) == 1)

rm(cps)
gc()

```

<!-- ### Build timing indicators -->

```{r develop CPS timing flags}
cps_timing <-
  cps_sub %>%
  mutate(
    baseline_year  = as.numeric(substr(as.character(CPSID), 1, 4)), 
    baseline_month = as.numeric(substr(as.character(CPSID), 5, 6)),
    months_since_base = (YEAR - baseline_year)*12 + (MONTH - baseline_month)
  )
  
table(cps_timing$months_since_base) # Values should be 0-3, 12-15 (CPS samples are interviewed for 4 consecutive months, not interviewed for the next 8 months, and then interviewed again for the next 4 months). There are some cases of 9-11 for months_since_base, but small enough to ignore. 

cps_timing <- 
  cps_timing %>% 
  mutate(
    .by = CPSID,
    
    is_baseline = months_since_base == 0,
    # /!\ This selects a single post-period survey. Notably, it's the first time in which
    # the household has been seen. That will standardize samples with respect to calendar
    # time, but not with respect to time since initial survey. Return to consider whether
    # this is okay, if we want to standardized by e.g. months_since_base == 12 or 15, or
    # if we want the baseline to be max(months_since_base) - 12.
    is_post     = months_since_base == max(months_since_base) & months_since_base >= 12,
    YEAR_MONTH  = paste(YEAR, str_pad(MONTH, side = "left", width = 2, pad = "0"), sep = "-")
  )

cps_timing_sub <- 
  cps_timing %>% 
  filter(
    is_baseline == TRUE | is_post == TRUE
  ) #subset to baseline or post data only

rm(cps_sub)
gc()
```

```{r examine how many cases have--or lack--baseline income data, eval = developer_mode}
# Examine which, and how many, household do not have baseline data.
cps_timing_sub %>% 
  summarize(
    .by = CPSID,
    has_baseline = max(is_baseline),
    has_month0   = max(months_since_base == 0)) %>% 
  mutate(
    YEAR_MONTH = substr(as.character(CPSID), 1, 6)
  ) %>% 
  summarize(
    .by = YEAR_MONTH,
    pct_has_baseline = mean(has_baseline),
    pct_has_month0   = mean(has_month0)
  ) %>% 
  arrange(YEAR_MONTH) %>% 
  pivot_longer(
    cols = -YEAR_MONTH
  ) %>%
  ggplot(
    aes(
      x = YEAR_MONTH,
      y = value,
      color = name,
      label = YEAR_MONTH)
  ) +
  geom_point() +
  geom_text(
    hjust = 1.1,
    angle = 90,
    color = "black",
    alpha = 0.8,
    size = 2
  ) +
  theme_minimal() +
  theme(
    axis.text.x = 
      element_text(
        angle = 90, 
        size = 6
      ),
    legend.position = "bottom"
  )

```

```{r tabulate months of available CPS data, eval = developer_mode}
# Examine available periods, by classification as baseline and post-period.

cps_timing_sub %>% 
  summarize(
    .by = c("is_baseline", "is_post", "YEAR"),
    n = comma(n())
  ) %>% 
  arrange(YEAR, is_baseline, is_post)

```


```{r recode cps data}
cps_recoded <- 
  cps_timing_sub %>% 
  mutate(
    
    # Create age groups
    cAge = 
      case_when(
        AGE %in%  0:5  ~ "Age0to5",
        AGE %in%  6:14 ~ "Age6to14",
        AGE %in% 15:19 ~ "Age15to19",
        AGE %in% 20:64 ~ "Age20to64",
        AGE >= 65      ~ "Age65plus"
      ),
    bAge0to5   = 1*(cAge == "Age0to5"),
    bAge6to14  = 1*(cAge == "Age6to14"),
    bAge15to19 = 1*(cAge == "Age15to19"),
    bAge20to64 = 1*(cAge == "Age20to64"),
    bAge65plus = 1*(cAge == "Age65plus"),
    
    bChild_of_Hoh = RELATE %in% c(301, 303),
      # 301 - child of head of household, 303 is step-child
    
    # Recode Gender
    cGender = 
      case_when(
        SEX == 1 ~ "male", 
        SEX == 2 ~ "female"
      ),
    bGender_M = 1*(cGender == "male"),
    bGender_F = 1*(cGender == "female"),
   
    # Recode Race 
    cRace = 
      case_when(
        RACE == 100 ~ "white",
        RACE == 200 ~ "black", 
        TRUE ~ "other_multiple"
      ),
    bHisp = 1 - 1*(HISPAN == 0),
    
    # Recode education
    cEduc =
      case_when(
        between(EDUC,   2,  71) ~ "LtHs", # This includes 12th grade with no diploma
        EDUC == 73              ~ "HS", 
        between(EDUC,  80, 110) ~ "SomeColl", # This includes Associate's, and years of college up to 4
        EDUC == 111             ~ "Coll",
        between(EDUC, 120, 125) ~ "Grad", # includes 5+ years of college or Master's, professional or doctorate
        TRUE ~ ""
      ),
    bEduc_LtHs     = 1*(cEduc == "LtHs"),
    bEduc_HS       = 1*(cEduc == "HS"),
    bEduc_SomeColl = 1*(cEduc == "SomeColl"),
    bEduc_Coll     = 1*(cEduc == "Coll"),
    bEduc_Grad     = 1*(cEduc == "Grad"),
    
    # Identify education enrollment status
    bSchAttend = 1*(SCHLCOLL %in% 1:4), 
      # This flags school attendance in high school or college, either full or part time
    
    bEmpl      = 1*(EMPSTAT == 10),
    bEmplLoose = 1*(EMPSTAT %in% c(10, 12, 34)), 
      # This includes 12 - "has job, but not at work last week", and Not in the Labor Force
      # for reasons other than housework, inability to work, unpaid work, retirement
      # The rationale for inclusion here is that this could possibly include reasons
      # related to training
    bLF        = 1*(LABFORCE == 2),
    
    usual_hrs_worked = 
      case_when(
        UHRSWORKT > 900 ~ NA,
        TRUE ~ UHRSWORKT
      ),
    bWork_elig              = 1*(bSchAttend | bEmpl),
    bWork_metHrsThresh_elig = 1*(bSchAttend | (bEmpl & (usual_hrs_worked >= work_hrs_threshold)))

    #cIndustry  = bin_industry(IND)
    
  )

```

```{r examine rates of employment status including codes for a loose definition of work qualification}
cps_recoded %>% 
  filter(
    bEmplLoose == 1,
  ) %>% 
  tabyl(EMPSTAT)
  # A large percentage of "loose" cases are not in the labor force -- many more
  # than having a job but not at work. Without more ability to be clear about 
  # what that represents, it's not recommended to use it
```


<!-- ### Develop household composition flags -->

<!-- These codes are consistent with being the householder themselves (RELATE == 101), which is by far the most common, or otherwise the child, parent, grandchild, or "other" relative. In short, because this implies that the head of household has no spouse present for whom FAMINC would ostensibly represent a combined income, we treat them as would-be single filers. -->

```{r develop family information relevant to calculating adjusted income and poverty status}

# Ensure that FAMINC is consistent within families
stopifnot(
  cps_recoded %>% 
    summarize(
      .by = c(YEAR, MONTH, YEAR_MONTH, CPSID),
      n_faminc_vals = length(unique(FAMINC))
    ) %>% 
    pull(
      n_faminc_vals
    ) %>% 
  unique() == 1
)

# Remove cases where all values of key fields 
missing_key_vals <- 
  cps_recoded %>% 
  summarize(
    .by = c(YEAR, MONTH, YEAR_MONTH, CPSID),
    all_work_NA       = all(is.na(bWork_elig)),
    all_workThresh_NA = all(is.na(bWork_metHrsThresh_elig))
  )
tabyl(missing_key_vals$all_work_NA) # None
tabyl(missing_key_vals$all_workThresh_NA) # This is a small percent of cases: about 1%
  # The result is ostensibly lack of information about usual hours worked
  # Instead of removing these cases, we will allow them to be NA

cps_family <- 
  cps_recoded %>% 
  summarize(
    .by = c(YEAR, MONTH, YEAR_MONTH, months_since_base, CPSID),
    fam_size = n(), 
    fam_wgt = sum(WTFINL),
    
    bAge0to5_present   = maxNA(bChild_of_Hoh & bAge0to5),
    bAge6to14_present  = maxNA(bChild_of_Hoh & bAge6to14),
    bAge15to19_present = maxNA(bChild_of_Hoh & bAge15to19),
    bAge0to14_present  = maxNA(bChild_of_Hoh & (bAge0to5 | bAge6to14)),
    
    bAdults_all_work_sch       = minNA(bWork_elig),
    bAdults_all_workThresh_sch = minNA(bWork_metHrsThresh_elig),
    
    bSpousePresent = maxNA(RELATE %in% 201:203),
    
    FAMINC = unique(FAMINC)
  ) %>% 
  mutate(
    bHas_schage_kid_base = 
      factor(
        bAge0to14_present,
        levels = 0:1, 
        labels = c("No Kid Age 0-14, Base", "Has Kid Age 0-14, Base")
      ),
    fSpouse_present = 
      factor(
        bSpousePresent,
        levels = 0:1, 
        labels = c("No Spouse Present, Base", "Spouse Present, Base")
      )
  )

```

```{r draw household income from categories and merge}

# Ensure that all FAMINC bounds are represented in the `faminc_bounds` recoding
stopifnot(
  all(
    unique(cps_family$FAMINC) %in%
      faminc_bounds$faminc
  )
)

cps_family <- 
  cps_family %>% 
  mutate(
    faminc_draw = draw_inc(FAMINC)
  )

cps_base_income <- 
  cps_family %>% 
  filter(
    months_since_base == 0
  ) %>% 
  select(CPSID, faminc_draw0 = faminc_draw)

cps_family_pov <- 
  cps_family %>% 
  merge(
    cps_base_income,
    by = "CPSID",
    all.x = TRUE
  )
```

```{r get fpl threshold for prog for CPS calcs}
# It's not strictly the case that this is provided directly by users, because a
# custom income threshold such as based on state median income may have been 
# provided

# /!\ Need to allow for multiple

prog_inc_thresh_fpl <- get_fpl_thresh_for_prog()
```

```{r ensure that all family sizes are in the FPL thresholds}
stopifnot(
  all(
    cps_family_pov$fam_size %>% 
      unique() %in%
      fpl_by_month$fpl_fam_size
  )
)
```

```{r check missings in family income}
# Check on missing values
if (FALSE) {
  cps_family_pov %>% 
    summarize(
      .by = c(months_since_base),
      nNAincome  =  sum(is.na(faminc_draw))  %>% comma(),
      rNAincome  = mean(is.na(faminc_draw))  %>% percent(),
      nNAincome0 =  sum(is.na(faminc_draw0)) %>% comma(),
      rNAincome0 = mean(is.na(faminc_draw0)) %>% percent()
    )  
}

```

```{r apply custom income thresholds if applicable}
# /!\ Should be refactored in, for future cases where custom income thresholds are in consideration
# # Determine which income ratio to use, based on whether custom values were specified
# if (exists("custom_income_thresh")) {
#   cps_pov_monthly[j = my_incratio := incratio_thresh]
# } else {
#   cps_pov_monthly[j = my_incratio := fam_incpov_ratio_adj]
#     # /!\ Note that previous implementations have use both "_adj" and non-adjusted
#     # income. This is something that deserves to be generalized, given that 
#     # this distinction will only be meaningful for estimation in time periods
#     # that intersects the COVID-19 pandemic, or represent other periods with 
#     # economic impact payments that impact income in a way that doesn't influence
#     # program eligibility
# }

# if (exists("custom_income_thresh")) {
#   # Check that all family sizes present in the data are represented in the custom
#   # spec file
#   stopifnot(
#     all(cps_family_pov$fam_size) %in% custom_income_thresh$fam_size
#   )
#   
#   cps_family_pov <- 
#     cps_family_pov %>% 
#     merge(
#       custom_income_thresh,
#       by = "fam_size",
#       all.x = TRUE
#     ) %>% 
#     mutate(
#       incratio_thresh = faminc_adj / inc_thresh
#     )
# }
```

```{r develop income to poverty ratio and program eligibility for cps}

cps_family_elig <-
  cps_family_pov %>% 
  
  # Develop ratios
  merge(
    fpl_by_month,
    by.x = c("fam_size", "YEAR", "MONTH"),
    by.y = c("fpl_fam_size", "fpl_year", "fpl_month"),
    all.x = TRUE
  ) %>% 
  mutate(
    fam_incpov_ratio = faminc_draw / fpl,
    
    # Bin family income
    cFam_incpov_ratio_cat_mix     = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 0.50, 1.00, 2.00, 4.00)),
    cFam_incpov_ratio_cat_by100   = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = seq(0, 4, by = 1.0)),
    cFam_incpov_ratio_cat_hs_prog = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 1.00, prog_inc_thresh_fpl/100, 4.00)),
    cFam_incpov_ratio_cat_with130 = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 0.75, 1.30, 2.00, 4.00)),
    # fam_incpov_ratio_cat_by50    = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = seq(0, 4, by = 0.5)),
    # fam_incpov_ratio_cat_by75    = bin_incpov_ratio(fam_incpov_ratio, pov_breaks = c(0, 0.75, 1.50, 2.25, 4.00)),
    
    # Develop character flags fro 
    cWorkElig       = ifelse(bAdults_all_work_sch       == 1, "WorkElig",       "NotWorkElig"),
    cWorkEligThresh = ifelse(bAdults_all_workThresh_sch == 1, "WorkEligThresh", "NotWorkEligThresh"),
    cSpousePresent  = ifelse(bSpousePresent == 1, "SpousePresent", "NoSpousePresent"),
    
    # Generate partition combining work and income bracket status
    cWork_incpov_status130 = paste_(cWorkElig, cFam_incpov_ratio_cat_with130),
    cWork_incpov_status100 = paste_(cWorkElig, cFam_incpov_ratio_cat_by100),
    cWork_incpov_statushs  = paste_(cWorkElig, cFam_incpov_ratio_cat_hs_prog),
    
    cWorkThresh_incpov_status130 = paste_(cWorkEligThresh, cFam_incpov_ratio_cat_with130),
    cWorkThresh_incpov_status100 = paste_(cWorkEligThresh, cFam_incpov_ratio_cat_by100),
    cWorkThresh_incpov_statushs  = paste_(cWorkEligThresh, cFam_incpov_ratio_cat_hs_prog),
    
    # Develop income measures to be used as outcomes of nowcasting
    bIncpov_le50  = 1*(fam_incpov_ratio <= 0.50),
    bIncpov_le100 = 1*(fam_incpov_ratio <= 1.00),
    bIncpov_le130 = 1*(fam_incpov_ratio <= 1.30),
    bIncpov_le138 = 1*(fam_incpov_ratio <= 1.38),
    bIncpov_le185 = 1*(fam_incpov_ratio <= 1.85),
    bIncpov_le200 = 1*(fam_incpov_ratio <= 2.00),
    bIncpov_le205 = 1*(fam_incpov_ratio <= 2.05),
    bIncpov_le225 = 1*(fam_incpov_ratio <= 2.25),
    bIncpov_le400 = 1*(fam_incpov_ratio <= 4.00)
  )
```

```{r create combinations of work and income eligibility flags}
for (x in local_prog_incratio_base) {
  new_name       <- glue("bProg_elig_incpov_{x}")
  new_nameThresh <- glue("bProg_eligThresh_incpov_{x}")
  cps_family_elig <- 
    cps_family_elig %>% 
    mutate(
      !!new_name       := 1*((fam_incpov_ratio < x/100) & bAdults_all_work_sch),
      !!new_nameThresh := 1*((fam_incpov_ratio < x/100) & bAdults_all_workThresh_sch)
    )
}
```


```{r quick memory cleanup}
rm(cps_family_pov, cps_timing, cps_timing_sub)
gc()
```


```{r merge program family measures into indiviudal records}

cps_elig <- 
  cps_recoded %>% 
  merge(
    cps_family_elig,
    by = c("YEAR", "MONTH", "YEAR_MONTH", "CPSID"),
    all.x = TRUE
  )

stopifnot(nrow(cps_recoded) == nrow(cps_elig))
```


<!-- Distinguish base vs post content -->

```{r subset to variables needed at baseline}
cps_base_prep <- 
  cps_elig %>% 
  filter(
    is_baseline == TRUE
  ) %>% 
  select(
    CPSID, CPSIDP, AGE, RELATE, WTFINL_base = WTFINL, HWTFINL_base = HWTFINL, 
    YEAR, MONTH, YEAR_MONTH, AGE, METRO, 
    fam_incpov_ratio, bSpousePresent,
    matches("^[bc](Age|Gender|Race|Educ|Empl)"), 
    matches("^[bc]Work"),
    matches("fam_incpov_ratio"),
    matches("work.+incpov_status")
  )
```

```{r create head of household characteristics and merge them in}
# Develop characteristics used for now-casting for head of household, for measures
# parallel to ACS5 predictors (with names that are also parallel)

if (FALSE) {
  # /!\ Note: not all cps_base records have a head of household
  cps_base_prep %>% 
    summarize(
      .by = CPSID, 
      has_hoh = sum(RELATE == 101)) %>% 
    pull(has_hoh) %>% 
    table()
}
  
cps_base_hoh <- 
  cps_base_prep %>% 
  filter(
    RELATE == 101
  ) %>% 
  mutate(
    rEd_LtHs     = bEduc_LtHs,
    rEd_Hs       = bEduc_HS,
    rEd_SomeColl = bEduc_SomeColl,
    rEd_Coll     = bEduc_Coll,
    rEd_Grad     = bEduc_Grad,
    
    rMarried = bSpousePresent,
    rUnmarriedMaleHh   = 1*(!bSpousePresent & bGender_M == 1),
    rUnmarriedFemaleHh = 1*(!bSpousePresent & bGender_F == 1)
  ) %>% 
  select(
    CPSID, matches("^rEd|rMarr|rUnmarr")
  )

# Add select characteristics used for now-casting predictions
cps_base <-
  cps_base_prep %>% 
  merge(
    cps_base_hoh,
    by = "CPSID"
  )

```


```{r subset to variables needed at post}
cps_post <- 
  cps_elig %>% 
  filter(
    is_post == TRUE,
    CPSID %in% cps_base$CPSID
  ) %>% 
  select(
    CPSID, CPSIDP, YEAR_MONTH, WTFINL_post = WTFINL, HWTFINL_post = HWTFINL,
    fam_incpov_ratio,
    matches("^(bIncPov|bProg_elig)")
  )
```


```{r clean up files}
rm(cps_base_income, cps_family, cps_family_elig, cps_recoded)
gc()
```

Check the correspondence between `cps_post` and `cps_base`.

```{r check percentage of households in base represented in post}
cps_base %>% 
  summarize(
    .by = YEAR_MONTH,
    base_in_post = mean(CPSID %in% cps_post$CPSID) %>% percent()
  )
```

```{r merge post into base}
cps_trans <- 
  merge(
    cps_base,
    cps_post,
    by = c("CPSID", "CPSIDP"),
    suffixes = c("_b", "_p"),
    all.x = TRUE
  )
```

<!-- Compare adjusted incomes directly, by subsets. Lots of noise here. This is the whole sample. -->

```{r compare incomes, eval = developer_mode}

inc_plot <- 
  cps_trans %>% 
  select(CPSID, matches("fam_incpov"), cAge, cWorkThresh_incpov_status130) %>% 
  unique() %>% 
  ggplot(
    aes(
      x = fam_incpov_ratio_b,
      y = fam_incpov_ratio_p
    )
  ) +
  geom_point(
    alpha = 0.05
  ) + 
  geom_abline(
    color = "blue", 
    linewidth = 1
  ) +
  geom_smooth(
    color = "red"
  )
print(inc_plot + facet_wrap(~cAge))
print(inc_plot + facet_wrap(~cWorkThresh_incpov_status130))
```

```{r}
save(
  cps_base, cps_post, cps_trans,
  file = glue("{output_path}cps_data_{my_output_tag}.Rda")
)
```
