<!-- This .Rmd file is set up to run either independently by checking for 
the presence of necessary objects in the global environment and running 
related scripts if not, or also as a child to the "main-doc". For that latter
reason, comments and headings that are not relevant to a final report to
pubic audiences are suppressed or moved to code chunks that can optionally be 
`echo`ed as desired. -->

```{r}
# run scripts for necessary packages and objects as necessary
if (!"meanNA"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("method--read-customization-file.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
```

<!-- # Prepare All Data ------------------------------------------------------->

```{r identify relevant fips codes}
my_state_fip <- 
  fips_codes %>% 
  filter(state == my_state_abbr) %>% 
  pull(state_code) %>% 
  unique()

if ("my_county" %in% objects()) {
  my_county_fip <- 
    fips_codes %>% 
    filter(
      state == my_state_abbr, 
      str_detect(county, my_county)
    ) %>% 
    pull(county_code) %>% 
    unique()
}
```


<!-- ## Load Geographic Data -------------------------------------------------->

<!-- ### Load Geographic Crosswalks ------------------------------------------->

```{r prepare geographic crosswalk data}
if (base_year <= 2021) {
  xwalk_source <- "https://www2.census.gov/geo/docs/maps-data/data/rel/2010_Census_Tract_to_2010_PUMA.txt"
  # We use 2010 crosswalks even up through 2021 because that is the geographic units 
  # utilized by 2021 ACS1 microdata (i.e. 2010 vintage PUMAs). 
  # See this reference for various connections between data release and 
  # vintage of related geographic boundaries:
  #   https://www.census.gov/programs-surveys/acs/geography-acs/geography-boundaries-by-year.2021.html#list-tab-626530102
} else {
  xwalk_source <- "https://www2.census.gov/geo/docs/maps-data/data/rel2020/2020_Census_Tract_to_2020_PUMA.txt"
}

geo_crosswalk_puma <-
  fread(xwalk_source) %>% 
    # for reference, this is the 2020 tract-to-PUMA crosswalk. While ACS5 data
    # from 2020 is available and uses this, the ACS1 data pull from 2021 uses
    # 2010 PUMA definitions. Temporarily, we are planning to continue to work on
    # a 2010 basis by pulling ACS5 data from 2019
    # 2010 crosswalk
    # 
  .[STATEFP == my_state_fip] %>% 
  # /!\ Am not aware of the significance of the FIP versus CE suffix. It's an 
  # assumption that there's no consequence to dropping the distinction
  rename(STATEFIP  = STATEFP,
         COUNTYFIP = COUNTYFP,
         TRACTFIP  = TRACTCE,
         PUMA      = PUMA5CE) %>% 
  mutate(STATEFIP  = str_pad(STATEFIP,  width = 2, side = "left", pad = "0"),
         TRACTFIP  = str_pad(TRACTFIP,  width = 6, side = "left", pad = "0"),
         COUNTYFIP = str_pad(COUNTYFIP, width = 3, side = "left", pad = "0"),
         PUMA      = str_pad(PUMA,      width = 5, side = "left", pad = "0"),
         GEOID     = paste0(STATEFIP, COUNTYFIP, TRACTFIP))

geo_crosswalk_zcta <-
  fread("https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_tract20_natl.txt") %>%
  rename(
    GEOID = GEOID_TRACT_20,
    ZCTA  = GEOID_ZCTA5_20
  ) %>% 
  mutate(
    GEOID         = str_pad(GEOID, width = 11, side = "left", pad = "0"),  #GEOID: 11-digit (concatenation of state, county, place, and tract)
    STATEFIP      = substr(GEOID, 1,2),
    AREALAND_PART = as.numeric(AREALAND_PART)
  ) %>%
  #restrict to my_state_fip
  .[STATEFIP == my_state_fip] %>%
  .[j = TRLANDPCT := AREALAND_PART / sum(AREALAND_PART),
    by = GEOID] %>%
  select(-STATEFIP) %>% 
  mutate(ZCTA = str_pad(ZCTA,  width = 5,  side = "left", pad = "0"))
    # See next chunk for defense/exploration of this approach for building a field
    # to apportion tract counts to ZCTAs
  # Source: https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.2020.html#zcta

#Warning: NAs produced by integer64 overflow
print(colSums(is.na(geo_crosswalk_zcta)))

geo_crosswalk <-
  merge(
    geo_crosswalk_puma,
    geo_crosswalk_zcta %>% dplyr::select(GEOID, ZCTA),
    by = "GEOID",
    all.x = TRUE
  ) %>% 
  data.table()

if (exists("my_county_fip")) {
  geo_crosswalk <- geo_crosswalk[COUNTYFIP == my_county_fip]
}
```

```{r compare 2010 and 2020 fields in zcta-to-tract crosswalk, eval = developer_mode}
# In the 2010 ZCTA-to-tract crosswalk, the TRPOPPCT field represented apportionment
# of population across ZCTA-to-tract overlaps -- "The Percentage of Total Population 
# of the 2010 Census Tract represented by the record." -- per the 2010 record 
# layout documentation:
#   https://www.census.gov/programs-surveys/geography/technical-documentation/records-layout/2010-zcta-record-layout.html

# There is no equivalent in the 2020 file:
#  https://www.census.gov/programs-surveys/geography/technical-documentation/records-layout/2020-zcta-record-layout.html
# However, there exists the `AREALAND_PART` which is the portion of the tract within
# the indicated ZCTA. This is analogous to the `TRAREALANDPCT` field in 2010.

# In this chunk, we look within the 2010 data to examine the correspondence between
# apportionment via population percentage (which is most desirable) vs via land
# percentage (which is the best available in 2020)
geo_crosswalk_zcta_2010 <- 
  fread("https://www2.census.gov/geo/docs/maps-data/data/rel/zcta_tract_rel_10.txt") %>%
  .[STATE == my_state_fip] %>% 
  .[j = GEOID := as.character(GEOID)] %>% 
  .[j = `:=`(pop_pct  = TRPOPPCT      / 100,
             land_pct = TRAREALANDPCT / 100)]

geo_crosswalk_zcta_2010 %>% 
  # Remove fully-contained tracts
  .[between(pop_pct, 0.05, 0.95)] %>% 
  ggplot(aes(x = pop_pct,
             y = land_pct)) +
  geom_abline() +
  geom_point(alpha = 0.3) +
  geom_smooth(color = "blue")
  # Bottom line -- there's a significant amount of scatter, but the trend
  # follows the 45 relatively closely. However, seems that small overlap areas can
  # overstated by land and larger overlap areas populations understated.
  # Note: because this is with respect to % portions of ZCTAs rather than overall
  # numbers, this is not equivalent to a story of overal low or high density,
  # but rather relatively lower or higher density within the given ZCTA.

geo_crosswalk_zcta_2010 %>% 
  # Remove fully-contained tracts
  .[between(pop_pct, 0.05, 0.95)] %>% 
  .[j = cor(pop_pct, land_pct)]
  # Correlation is 0.8, after trimming away extremes with respect to population pct  
```

```{r auto pull of tract, puma, county, and school district shapefiles}
# Declare which vintage of Census TIGER shapefiles should be pulled
tiger_year <- base_year

# Set up input to tigris functions for pulling by county
# Note that because the "else" value is NULL, the ifelse() has a problem
if (exists("my_county_fip")) county_val <- my_county_fip else county_val <- NULL

# Note that cb = TRUE requests a lower-res file, which is fine for mapping we want to do
try(tractShp  <-   tracts(state = my_state_fip, cb = TRUE, year = tiger_year, county = county_val), silent = T)
try(pumaShp   <-    pumas(state = my_state_fip, cb = TRUE, year = tiger_year), silent = T)
try(countyShp <- counties(state = my_state_fip, cb = TRUE, year = tiger_year), silent = T)
try(zctaShp   <-    zctas(cb = TRUE, year = tiger_year, starts_with = zcta_starts), silent = T)
  # Note: we pull zctas differently--with "starts_with" rather than state because
  # the zctas() function can only return by state for years 2000 and 2010 

# Download school district file from Census using tigris package
try(elShp <- school_districts(state = {my_state_fip}, type = 'elementary', year = tiger_year + 1), silent = T)
try(scShp <- school_districts(state = {my_state_fip}, type = 'secondary',  year = tiger_year + 1), silent = T)
try(unShp <- school_districts(state = {my_state_fip}, type = 'unified',    year = tiger_year + 1), silent = T)

# Clean data
schoolShp <- 
  bind_rows(elShp %>% mutate(level = "elementary"), 
            unShp %>% mutate(level = "unified"))

# schoolShp_sec_included <- 
#   bind_rows(elShp %>% mutate(level = "elementary"), 
#             scShp %>% mutate(level = "secondary"),
#             unShp %>% mutate(level = "unified"))

# Display school district shapefile
ggplot() + 
  geom_sf(data = schoolShp,
          aes(fill = level)) +
  theme_void()

  
# We only use elementary and unified school districts.
rm(elShp, unShp, scShp) # , schoolShp_sec_included
```

```{r pull puma and zcta shapefiles from Census website if not available from the tigris package pulls above}
if (!exists("pumaShp", envir = .GlobalEnv)) {
  pumafile <- glue("{input_path}tl_{tiger_year}_{my_state_fip}_puma20.shp")
  if (!file.exists(pumafile)) {
    census_path       <- glue("https://www2.census.gov/geo/tiger/TIGER{tiger_year}/PUMA/")
    download_filename <- glue("state_{my_state_fip}_puma20.zip")
    download.file(url      = glue("{census_path}tl_{tiger_year}_{my_state_fip}_puma20.zip"),
                  destfile = glue("{input_path}{download_filename}"))
    unzip(glue("{input_path}{download_filename}"),
          exdir = str_replace(input_path, "\\/$", ""))
  }
  pumaShp <- st_read(pumafile)
  rm(pumafile)
}

if (!exists("zctaShp", envir = .GlobalEnv)) {
  zctafile <- glue("{input_path}tl_{tiger_year}_us_zcta520.shp")
  if (!file.exists(zctafile)) {
    census_path       <- glue("https://www2.census.gov/geo/tiger/TIGER{tiger_year}/ZCTA520/")
    download_filename <- glue("us_zcta520.zip")
    download.file(url      = glue("{census_path}tl_{tiger_year}_us_zcta520.zip"),
                  destfile = glue("{input_path}{download_filename}"))
    unzip(glue("{input_path}{download_filename}"),
          exdir = str_replace(input_path, "\\/$", ""))
  }
  zctaShp <- st_read(zctafile)
  rm(zctafile)
}
```

```{r rename certain fields in shapefiles to agree with those in the crosswalks}
tractShp <- 
  tractShp %>%
  setnames(old = c("STATEFP", "COUNTYFP", "TRACTCE"),
           new = c("STATEFIP", "COUNTYFIP", "TRACTFIP"),
           skip_absent = TRUE)

if (base_year <= 2021) {
  pumaShp <- 
    pumaShp %>%
    setnames(old = c("STATEFP10", "PUMACE10", "GEOID10"),
             new = c("STATEFIP",  "PUMA",     "GEOID"),
             skip_absent = TRUE)
  
  zctaShp <-
    zctaShp %>% 
    setnames(old = c("ZCTA5CE10", "GEOID10"),
             new = c("ZCTA",      "GEOID"),
             skip_absent = TRUE)
} else {
  pumaShp <- 
    pumaShp %>%
    setnames(old = c("STATEFP20", "PUMACE20", "GEOID20"),
             new = c("STATEFIP",  "PUMA",     "GEOID"),
             skip_absent = TRUE)

  zctaShp <-
    zctaShp %>% 
    setnames(old = c("ZCTA5CE20", "GEOID20"),
             new = c("ZCTA",      "GEOID"),
             skip_absent = TRUE)
    
}

countyShp <-
  countyShp %>% 
  setnames(old = c("STATEFP",  "COUNTYFP",  "NAME"),
           new = c("STATEFIP", "COUNTYFIP", "County"),
           skip_absent = TRUE)

schoolShp <-
  schoolShp %>% 
  setnames("NAME",
           "school",
           skip_absent = TRUE)
```

```{r adds tract-SD crosswalk from NCES}
# schoolShp downloaded from the Census does not contain tract information
# Crosswalk can be downloaded from the National Center for Education Statistics
# Reference: https://nces.ed.gov/programs/edge/geographic/relationshipfiles
# Note that school districts are updated every year
grffile <- glue("{input_path}GRF24/grf24_lea_tract.xlsx")
if (!file.exists(grffile)) {
  download.file(url      = glue("https://nces.ed.gov/programs/edge/data/GRF24.zip"),
            destfile = glue("{input_path}GRF24.zip"))
  unzip(glue("{input_path}GRF24.zip"),
        exdir = str_replace(input_path, "\\/$", ""))
}

geo_crosswalk_sd <-
  readxl::read_xlsx(grffile) %>% 
  rename(school = NAME_LEA24,
         GEOID  = TRACT) %>% 
  mutate(STATEFIP = substr(GEOID, 1, 2),
         LANDAREA = as.numeric(LANDAREA)) %>% 
  filter(STATEFIP == {my_state_fip})

geo_crosswalk_sd <- geo_crosswalk_sd %>% 
  merge(schoolShp %>% as.data.frame() %>% select(GEOID, level) %>% unique(),
        by.x = "LEAID",
        by.y = "GEOID",
        all.x = TRUE) %>% 
  filter(level %in% c("elementary", "unified")) %>% 
  mutate(LAND_SQMETER  = LANDAREA*2589988.110336)

geo_crosswalk_sd <- geo_crosswalk_sd %>%
  group_by(GEOID) %>% 
  mutate(pct_sd = LANDAREA / sum(LANDAREA))

rm(grffile)
```


```{r check land area data}
#compare land area from crosswalk to schoolShp
geo_crosswalk_sd_area <- geo_crosswalk_sd %>% 
  group_by(LEAID) %>% 
  mutate(ALAND = sum(LAND_SQMETER))

schoolShp_area <- schoolShp %>% 
  select(GEOID, STATEFP, ELSDLEA, UNSDLEA, school, level, geometry, ALAND) %>% 
  merge(geo_crosswalk_sd_area %>% as.data.frame() %>% select(LEAID, ALAND) %>% unique(),
        by.x = "GEOID",
        by.y = "LEAID",
        all.x = TRUE) %>% 
  mutate(pct_diff = (ALAND.x - ALAND.y)/ALAND.x)

summary(schoolShp_area$pct_diff)

if (FALSE) {
  schoolShp_area %>% filter(is.na(pct_diff)) %>% View()
}

#check sum of land area to Census tract
geo_crosswalk_sum_area <- geo_crosswalk_sd %>% 
  group_by(GEOID) %>% 
  mutate(sum_sd = sum(LAND_SQMETER)) %>% 
  merge(tractShp %>% as.data.frame() %>% select(GEOID, ALAND) %>% unique(),
        by = "GEOID",
        all.x = TRUE) %>%
  mutate(pct_diff = abs((ALAND - sum_sd)/sum_sd)) 

summary(geo_crosswalk_sum_area$pct_diff)

if (FALSE) {
  geo_crosswalk_sum_area %>% arrange(desc(pct_diff)) %>% View()
}

if (str_detect(my_output_tag, "IECAM")) {
  #Check 8804.27 in Plainfield
  tractShp %>% filter(GEOID == 17197880427) %>% View()
  schoolShp %>% filter(school %like% "Plainfield") %>% View()
  #See the following websites for the maps:
  #https://censusreporter.org/profiles/97000US1731740-plainfield-school-district-202-il/
  #https://censusreporter.org/profiles/14000US17197880427-census-tract-880427-will-il/
}

rm(geo_crosswalk_sd_area, schoolShp_area, geo_crosswalk_sum_area)
```


```{r add county name to geo_crosswalk help label estimates}
geo_crosswalk <- 
  geo_crosswalk %>% 
  merge(countyShp %>% as.data.frame() %>% select(COUNTYFIP, County) %>% unique(),
        by = "COUNTYFIP",
        all.x = TRUE)
```

```{r load and feed in any auxiliary geographies}

if (exists("my_aux_geo")) {
  
  # Read in auxiliary data shape
  auxShp <- st_read(glue("{input_path}{my_aux_geo}"))
  
  # Give a generic name to the aux geography's label field
  auxShp$aux_geo_label <- auxShp %>% pull(get(my_aux_geo_field))

  # Reproject if necessary
  if (st_crs(auxShp) != st_crs(tractShp)) {
    auxShp <- 
      st_transform(
        auxShp,
        crs = st_crs(tractShp)
      )
  }
  
  # Handle potential issues with duplicate vertices
  auxShp <- st_make_valid(auxShp)
  
  # Attempt to identify intersections
  tract_aux_intersection <- 
    st_intersection(
      tractShp,
      auxShp
    )
    # This returns all geographies of tract sliced by aux, i.e. 
    # representing potential duplicates
  sf_use_s2(FALSE)
    # This above step is recommended to avoid findings of degenerate geometries due
    # to duplicate vertices: https://github.com/r-spatial/sf/issues/1762
  
  tract_aux_intersection$area <- as.numeric(st_area(tract_aux_intersection))
  
  # Examine duplicates to see whether any existing duplicates 
  if (FALSE) {
    tract_aux_intersection %>% 
      group_by(GEOID) %>% 
      filter(n() > 1) %>% 
      select(GEOID, aux_geo_label, area) %>% 
      arrange(GEOID) %>% 
      View()
  }
  
  # Merge the original tract file into this intersections file to be able to
  # reference the total area of each tract
  # Note: we do this instead of relying on sum(area) because tract_aux_intersection
  # represents only polygons that intersect with the aux geography, which can
  # fully remove portions of tracts that are outside of the aux boundaries, leading
  # to erroneous filtering and proration of tract-level statistics
  tract_area <- 
    tractShp %>% 
    mutate(tract_area = as.numeric(st_area(tractShp)))
  
  tract_aux_intersection_pcts <- 
    tract_aux_intersection %>% 
    # Merge tract_area contents as new data.frame (which drops the geometry field,
    # and avoids errors)
    merge(
      with(
        tract_area,
        data.frame(GEOID = GEOID,
                   tract_area = tract_area)),
      all.x = TRUE
    ) %>% 
    mutate(
      .by = GEOID,
      pct_area = area / tract_area
    )
  
  # Subset intersected geographies to those with areas that are within 2 orders of
  # magnitude of the largest. This is primarily to rule out idiosyncratic overlaps
  
  # Examine the histogram of prorations
  if (FALSE) {
    ggplot(tract_aux_intersection_pcts %>% filter(str_detect(NAME.1, "District 299"))) + 
      geom_histogram(aes(x = pct_area))
  }
  
  geo_crosswalk_aux <- 
    tract_aux_intersection_pcts %>% 
    # filter(pct_area > 0.01)
    filter(pct_area >= 0.10)
  
  # Recalculate percentages within tract to reestablish adding-up to 100%
  
  geo_crosswalk_aux <- 
    geo_crosswalk_aux %>% 
    mutate(
      .by = GEOID,
      pct_area = pct_area / sum(pct_area)
    )
  
  #stopifnot(any(table(tract_aux_intersection_keep$GEOID) > 1) == FALSE)
  
  # If the user opts to do so, intersect the county file with the auxiliary layer
  if (intersect_county_and_aux) {
    # Use the geo_crosswalk_aux to identify:
    # (1) which counties overlap with the aux geo
    # (2) within those counties, which tracts are/are not in the aux geo
    # (3) swap these distinctions into the geo
    geo_crosswalk <- 
      geo_crosswalk %>% 
      merge(
        geo_crosswalk_aux %>% select(one_of(c("GEOID", my_aux_geo_field, "pct_area"))),
        by = "GEOID",
        all.x = TRUE
      ) %>% 
      setnames(
        my_aux_geo_field,
        "my_aux_geo_field"
      ) %>% 
      # Flag whether the tract is present inside of the auxiliary geography
      mutate(
        in_aux_flag = ifelse(!is.na(my_aux_geo_field), 1, 0)
      ) %>% 
      # By county, if no tracts are in the aux geography, maintain the county name
      # Otherwise, if there is some intersection, rename
      mutate(
        .by = "County",
        County = 
          case_when(
            max(in_aux_flag) == 0 ~ County,
            in_aux_flag      == 0 ~ paste(County, glue("(Non-{my_aux_overall_name})")),
            in_aux_flag      == 1 ~ paste(County, glue("({my_aux_overall_name})"))
          ),
        pct_area = ifelse(is.na(pct_area), 1, pct_area)) %>% 
      mutate(
        County = ifelse(County %like% "DuPage", "DuPage", County)
      )
    
    if (FALSE) {
      cbind(
        geo_crosswalk     %>% filter(chicago_flag == 1) %>% select(GEOID, pct_area) %>% arrange(GEOID), 
        geo_crosswalk_aux %>%                               select(GEOID, pct_area) %>% arrange(GEOID))
    }
  }
} else {
  geo_crosswalk <- 
    geo_crosswalk %>% 
    mutate(pct_area = 1)
}
```

```{r checks the total area land}
sum(tractShp$ALAND)
sum(schoolShp$ALAND)
sum(countyShp$ALAND)

sum(geo_crosswalk_zcta$AREALAND_PART)
sum(geo_crosswalk_sd$LAND_SQMETER)

if (str_detect(my_output_tag, "IECAM")) {
  geo_crosswalk_b5 %>% mutate(LANDAREA_SQM = LANDAREA*2589988.110336) %>% pull(LANDAREA_SQM) %>% sum()  
}
```

```{r collect and save GIS data}
geo_objects <- c("my_state_fip", "geo_crosswalk", "geo_crosswalk_zcta", "geo_crosswalk_sd", "tractShp", "pumaShp", "countyShp", "zctaShp", "schoolShp", "leaflet_base_map")
if (exists("auxShp"))        geo_objects <- c(geo_objects, "auxShp", "geo_crosswalk_aux")
if (exists("my_county_fip")) geo_objects <- c(geo_objects, "my_county_fip")
if (str_detect(my_output_tag, "IECAM"))  geo_objects <- c(geo_objects, "geo_crosswalk_b5")
if (str_detect(my_output_tag, "CECIDS")) geo_objects <- c(geo_objects, "geo_crosswalk_distr")
```


```{r save applicable GIS objects}
save(list = geo_objects,
     file = glue("{output_path}geo_data_{my_output_tag}.Rda"))
```
